FORMAT: 1A
HOST: http://buscacursosplusplus.apiblueprint.org/

# Buscacursos++

Esta API permite hacer un CRUD de reviews de cursos y profesores que se encuentran en una aplicación RoR.


## Colección de Reviews [/reviews]

### Lista todos los Reviews  [GET]

Queda pendiente 
+ Request (application/json)

+ Response 201 (application/json)
        
    

### Crear un nuevo review [POST]

Crea un nuevo review, adjuntando los datos del curso y el usuario en un JSON.

+ Request (application/json)
    + Headers
    
            Authorization: oauth_token
            
    + Body

            {
                "course": {
                    "name": "Desarrollo de Sofware",
                    "number": "IIC3143"
                },
                "content": "Este curso es el mejor que he tomado este semestre",
            }

+ Response 201 (application/json)

            {
                "status":"success",
                "data": 
                    {
                        "course": "Desarrollo de Sofware",
                        "number": "IIC3143",
                        "created_at": "2018-05-22T21:17:20.132Z",
                        "updated_at": "2018-05-22T21:17:20.132Z",
                        "url": "http://localhost:3000/courses/1.json",
                        "reviews": [ 
                            {
                                "id": 2,
                                "created_at": "2018-05-22T21:23:16.850Z",
                                "updated_at": "2018-05-22T21:23:16.850Z",
                                "content": "Este curso es el mejor que he tomado este semestre",
                                "url": "http://localhost:3000/reviews/2.json",
                                "author": {
                                    "first_name": "IGNACIO",
                                    "last_name": "HERMOSILLA CORNEJO",
                                    "picture": "https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M/photo.jpg"
                                },
                                "like_total" : 0,
                                "like_authors": []
                            }
                        ]
                    }   
                
            }
        
+ Request Edge case (application/json)
    + Headers
    
            Authorization: oauth_token
            
    + Body

            {
                "course": {
                    "name": "Desarrollo de Sofware",
                    "number": "IIC3143"
                },
                "content": ""
            }
            
+ Response 401 (application/json)

            {
                "status": "fail",
                "data": {
                    "message": "Empty Review"
                }
            }




## Review [/review/1]


### Actualizar Review [PUT]
Edita el Texto de una review del mismo usuario
        
+ Request  (application/json)
    + Headers
    
            Authorization: oauth_token
            
    + Body

            {
                "content": "nuevo contenido para el review"
            }
            
+ Response 200 (application/json)

            {
                "status": "succes",
                "data": {
                    "id": 1,
                    "name": "Desarrollo de Software",
                    "number": "IIC3143",
                    "created_at": "2018-05-22T21:17:20.132Z",
                    "updated_at": "2018-05-22T21:17:20.132Z",
                    "url": "http://localhost:3000/courses/1",
                    "reviews": [
                        {
                            "id": 16,
                            "created_at": "2018-05-23T07:07:51.719Z",
                            "updated_at": "2018-05-23T07:07:56.394Z",
                            "content": "Poner aca el nuevo texto de nuestra review",
                            "url": "http://localhost:3000/reviews/16",
                            "author": {
                                "first_name": "IGNACIO",
                                "last_name": "HERMOSILLA CORNEJO",
                                "picture": "https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M/photo.jpg"
                            },
                            "like_total" : 0,
                            "like_authors": []
                        }
                    ]
                }
            }

### Borrar Review [DELETE]
Elimina una review del mismo usuario
+ Request  (application/json)
    + Headers
    
            Authorization: oauth_token
            
        
+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "message": "ok"
            }
        }
   
## Like a review [/review/1/like]

### Like a un review [POST]
Usuario le da un like al review
+ Request (application/json)
    + Headers
    
            Authorization: oauth_token
            
            
+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "message": "ok"
            }
        }
            

### Unlike a un review [DELETE]
Usuario le da un like al review
+ Request (application/json)
    + Headers
    
            Authorization: oauth_token

+ Response 200 (application/json)

        {
            "status": "success",
            "data": {
                "message": "ok"
            }
        }


## Colección de un curso [/courses/IIC3143]



### Lista Reviews curso especifico [GET]
Enviar datos de un curso y recibir lista de sus reviews

+ Request  (application/json)
    + Headers

            Authorization: oauth_token
        
+ Response 200  (application/json)


        {
            "status":"success",
            "data": 
                {
                "name": "Desarrollo de Sofware",
                "number": "IIC3143",
                "created_at": "2018-05-22T21:17:20.132Z",
                "updated_at": "2018-05-22T21:17:20.132Z",
                "url": "http://localhost:3000/courses/1.json",
                "reviews": [ 
                    {
                        "id": 1,
                        "created_at": "2018-05-22T21:23:16.836Z",
                        "updated_at": "2018-05-22T21:23:16.836Z",
                        "content": "Excelente review 1",
                        "url": "http://localhost:3000/reviews/1.json",
                        "author": {
                            "first_name": "IGNACIO",
                            "last_name": "HERMOSILLA CORNEJO",
                            "picture": "https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M/photo.jpg"
                        },
                        "like_total" : 2,
                        "like_authors": [
                            {
                                "first_name": "MARIO",
                                "last_name": "CEPEDA GONZALES",
                                "picture": "https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M/photo.jpg"
                            },
                            {
                                "first_name": "MAGADALENA",
                                "last_name": "HURTADO ECHEÑAQUI",
                                "picture": "https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M/photo.jpg"
                            }
                        ]
                    },
                    {
                        "id": 2,
                        "created_at": "2018-05-22T21:23:16.850Z",
                        "updated_at": "2018-05-22T21:23:16.850Z",
                        "content": "Excelente review 2",
                        "url": "http://localhost:3000/reviews/2.json",
                        "author": {
                            "first_name": "IGNACIO",
                            "last_name": "HERMOSILLA CORNEJO",
                            "picture": "https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M/photo.jpg"
                        },
                        "like_total" : 0,
                        "like_authors": []
                    }
                ]
                }
            
        }